apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  namespace: default
spec:
  containers:
    - name: busybox-container
      image: busybox
      command:
        - "sleep"
      args:
        - "1000"